name: Build S23 FE Kernel (Exynos 2200)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison flex git make \
          libncurses5-dev libssl-dev python3 python3-pip ccache \
          zip unzip wget curl tar xz-utils

    - name: Download Clang
      run: |
        mkdir -p ~/toolchains
        cd ~/toolchains
        wget https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/clang-r416183b.tar.gz -O clang.tar.gz
        mkdir clang-r416183b && tar -xf clang.tar.gz -C clang-r416183b
        echo "CLANG_PATH=$HOME/toolchains/clang-r416183b/bin" >> $GITHUB_ENV

    - name: Download ARM GNU Toolchain
      run: |
        cd ~/toolchains
        wget https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        tar -xf arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
        echo "GCC_PATH=$HOME/toolchains/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu/bin" >> $GITHUB_ENV

    - name: Build Kernel
      run: |
        export PATH=$CLANG_PATH:$GCC_PATH:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        export CC=clang
        export CROSS_COMPILE=aarch64-none-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-none-linux-gnueabi-

        # substitua "defconfig" pelo defconfig do S23 FE Exynos 2200
        make <s5e9925-r11sxxx_defconfig> -j$(nproc)
        make -j$(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build
        path: arch/arm64/boot/Image.gz-dtb
